routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\DanhmucController;
use App\Http\Controllers\TruyenController;
use App\Http\Controllers\ChapterController;
use App\Http\Controllers\ChapterTranhController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\TheloaiController;
use App\Http\Controllers\GoogleController;
use App\Http\Controllers\FacebookController;
use App\Http\Controllers\InformationController;
use App\Http\Controllers\TruyenTranhController;
use App\Http\Controllers\SachController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\GoogleDrive;
use App\Http\Controllers\Auth\LoginController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [IndexController::class,'home']);
Route::get('/sachtruyen_admin', [LoginController::class,'login'])->name('login');
Route::get('/danh-muc/{slug}', [IndexController::class,'danhmuc']);
Route::get('/xem-truyen/{slug}', [IndexController::class,'xemtruyen']);
Route::get('/xem-chapter/{slug_truyen}/{slug}', [IndexController::class,'xemchapter']);
Route::get('/xem-truyen-tranh/{slug_truyen}/{slug}', [IndexController::class,'xemtruyentranh']);
Route::get('/the-loai/{slug}', [IndexController::class,'theloai']);

Route::get('/doc-sach', [IndexController::class,'docsach']);
Route::post('/xemsachnhanh', [IndexController::class,'xemsachnhanh']);

Route::get('/truyen-tranh', [IndexController::class,'truyentranh']);
Route::get('/truyen-tranh/{slug}', [IndexController::class,'truyentranh']);
Route::get('/tag/{tag}', [IndexController::class,'tag']);
Route::post('/show-tranh', [IndexController::class,'show_tranh']);
Route::post('/autocomplete-ajax',[IndexController::class,'autocomplete_ajax']);
Route::post('/tim-kiem', [IndexController::class,'timkiem']);
Route::post('/truyennoibat', [TruyenController::class,'truyennoibat']);
Route::post('/tabs-danhmuc', [IndexController::class,'tabs_danhmuc']);
Route::get('/kytu/{kytu}', [IndexController::class,'kytu']);

Route::get('dang-ky', [IndexController::class,'dangky'])->name('dang-ky');
Route::get('dang-nhap', [IndexController::class,'dangnhap'])->name('dang-nhap');
Route::get('dang-xuat', [IndexController::class,'sign_out'])->name('dang-xuat');
Route::get('yeu-thich', [IndexController::class,'yeu_thich'])->name('yeu-thich');
Route::get('xoayeuthich/{id}', [IndexController::class,'xoayeuthich'])->name('xoayeuthich');
Route::post('register-publisher', [IndexController::class,'register_publisher'])->name('register-publisher');
Route::post('login-publisher', [IndexController::class,'login_publisher'])->name('login-publisher');
Route::post('themyeuthich', [IndexController::class,'themyeuthich'])->name('themyeuthich');
Route::post('comment', [IndexController::class,'comment'])->name('comment');
Auth::routes();
// Auth::routes([
//   'register' => false, // Registration Routes...
//   'reset' => false, // Password Reset Routes...
//   'verify' => false, // Email Verification Routes...
  
// ]);
Route::group(['middleware' => ['auth']], function() {
	
	Route::resource('/danhmuc', DanhmucController::class);
	Route::resource('/truyen', TruyenController::class);
	Route::resource('/sach', SachController::class);
	Route::resource('/chapter', ChapterController::class);
	Route::resource('/theloai', TheloaiController::class);
	Route::resource('/information', InformationController::class);
	Route::resource('/truyentranh', TruyenTranhController::class);
	Route::resource('/chaptertranh', ChapterTranhController::class);
	Route::get('chapter_truyentranh/{slug}', [ChapterTranhController::class, 'chapter_truyentranh']);
	Route::get('delete-file/{filename}/{extension}/{timestamp}', [ChapterTranhController::class, 'delete_file']);

	Route::get('/home', [UserController::class, 'index'])->name('home');
	Route::get('/impersonate/user/{id}', [UserController::class,'impersonate']);
	Route::get('/user/stopImpersonate', [UserController::class,'stopImpersonate']);


	Route::get('list-comment', [TruyenController::class,'list_comment'])->name('list-comment');
	Route::post('active_comment', [TruyenController::class,'active_comment'])->name('active_comment');
	
});

Route::get('auth/google', [GoogleController::class, 'redirectToGoogle']);
Route::get('auth/google/callback', [GoogleController::class, 'handleGoogleCallback']);

Route::get('auth/facebook', [FacebookController::class, 'redirectToFacebook']);
Route::get('auth/facebook/callback', [FacebookController::class, 'handleFacebookCallback']);

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
     \UniSharp\LaravelFilemanager\Lfm::routes();
 });

Route::get('/storage-link', function(){
    return Artisan::call('storage:link');
    
});
Route::get('/create-sitemap', function(){
    return Artisan::call('sitemap:create');
   
});
Route::get('/custom_error', function(){
    return Artisan::call('php artisan vendor:publish --tag=laravel-errors');
  
});

Route::get('/assignRole/{id}', [HomeController::class, 'assignRole']);
Route::post('/insert_roles/{id}', [HomeController::class, 'insert_roles']);

app/Http/Controllers/ChapterTranhController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Chapter;
use App\Models\Truyen;
use App\Models\FileGGDrive;
use Carbon\Carbon;
use Storage;
use File;
class ChapterTranhController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $chapter = Chapter::with('truyen')->where('loaichapter','=','truyentranh')->orderBy('id','DESC')->get();
        //dd($chapter);
        return view('admincp.chaptertranh.index')->with(compact('chapter'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $truyen = Truyen::orderBy('id','DESC')->where('loaitruyen','=','truyentranh')->get();
        return view('admincp.chaptertranh.create')->with(compact('truyen'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    
    public function store(Request $request)
    {
        $data = $request->validate(
            [
                'tieude' => 'required|max:255',
                'slug_chapter' => 'required|max:255',
                'tomtat' => 'required',
                'kichhoat' => 'required',
                'truyen_id' => 'required',
            ],
            [
                'slug_chapter.unique' => 'Slug đã có ,xin điền slug khác',
                'tieude.unique' => 'Tiêu đề đã có ,xin điền tiêu đề khác',
                'tieude.required' => 'Tiêu đề phải có nhé',
                'tomtat.required' => 'Tóm tắt chapter phải có nhé',
                
                'slug_chapter.required' => 'Slug chapter phải có',
                
            ]
        );
        // $data = $request->all();
        // dd($data);
        $chapter = new Chapter();
        $chapter->tieude = $data['tieude'];
        $chapter->slug_chapter = $data['slug_chapter'];
        $chapter->created_at = Carbon::now('Asia/Ho_Chi_Minh');
        $chapter->tomtat = $data['tomtat'];
        $chapter->noidung = 'noidungtruyentranh';
        $chapter->kichhoat = $data['kichhoat'];
        $chapter->truyen_id = $data['truyen_id'];
        $chapter->loaichapter = 'truyentranh';
        $chapter->save();
        //upload to google drive
        $truyen = Truyen::find($data['truyen_id']);

        $dir = '/';
        $recursive = true; // Get subdirectories also?
        $contents = collect(Storage::disk('google')->listContents($dir, $recursive));

        $dir_truyen = $contents->where('type', '=', 'dir')
            ->where('filename', '=', $truyen->slug_truyen)
            ->first(); 
         

        if ( ! $dir) {
            return redirect()->back()->with('status','Thư mục truyện tranh không tồn tại trong google drive,check lại nhé.');
        }
        // Create sub dir
        Storage::disk('google')->makeDirectory($dir_truyen['path'].'/'.$data['slug_chapter']);
        
       

        //upload multiple file to dir ggdrive
        $dir_img = '/';
        $recursive_img = true; // 
        $contents_image = collect(Storage::disk('google')->listContents($dir_img, $recursive_img));

        $dir_chapter = $contents_image->where('type', '=', 'dir')
                ->where('filename', '=', $data['slug_chapter'])
                ->first();    
        //Change permission for sub dir chapter
        $service = Storage::disk('google')->getAdapter()->getService();
        $permission = new \Google_Service_Drive_Permission();
        $permission->setRole('reader');
        $permission->setType('anyone');
        $permission->setAllowFileDiscovery(false);
        $permissions = $service->permissions->create($dir_chapter['basename'], $permission);  
        $files = $request->file('files');
            if($request->hasFile('files')){

            foreach ($files as $file) {

                $name = $file->getClientOriginalName();
               
                Storage::disk('google')->put($dir_chapter['path'].'/'.$name,File::get($file));

            }
        }
        //store file into db
        //  // For simplicity, this folder is assumed to exist in the root directory.
        // $folder = $data['slug_chapter'];

        // // Get root directory contents...
        // $contents = collect(Storage::disk('google')->listContents('/', true));

        // // Find the folder you are looking for...
        // $dir_folder_file = $contents->where('type', '=', 'dir')
        //     ->where('filename', '=', $folder)
        //     ->first(); // There could be duplicate directory names!

        // if ( ! $dir_folder_file) {
        //     return 'No such folder!';
        // }

        // // Get the files inside the folder...
        // $files = collect(Storage::disk('google')->listContents($dir_folder_file['path'], false))
        //         ->where('type', '=', 'file');
       
        // foreach($files as $key => $file){
        //     $fileggdrive = new FileGGDrive();
        //     $fileggdrive->name = $data['slug_chapter'].'-'.$file['name'];
        //     $fileggdrive->type = $file['type'];
        //     $fileggdrive->path = $file['path'];
        //     $fileggdrive->filename = $file['filename'];
        //     $fileggdrive->extension = $file['extension'];
        //     $fileggdrive->timestamp = $file['timestamp'];
        //     $fileggdrive->mimetype = $file['mimetype'];
        //     $fileggdrive->size = $file['size'];
        //     $fileggdrive->dirname = $file['dirname'];
        //     $fileggdrive->basename = $file['basename'];
        //     $fileggdrive->chapter_id = $chapter->id;
          
        //     $fileggdrive->save();
        // }

        return redirect()->back()->with('status','Thêm chapter truyện tranh thành công');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $chapter = Chapter::find($id);
        $truyen = Truyen::where('loaitruyen','=','truyentranh')->orderBy('id','DESC')->get();
        return view('admincp.chaptertranh.edit')->with(compact('truyen','chapter'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $data = $request->validate(
            [
                'tieude' => 'required|max:255',
                'slug_chapter' => 'required|max:255',
                
                'tomtat' => 'required',
                'kichhoat' => 'required',
                'truyen_id' => 'required',
            ],
            [
                'slug_chapter.unique' => 'Slug đã có ,xin điền slug khác',
                'tieude.unique' => 'Tiêu đề đã có ,xin điền tiêu đề khác',
                'tieude.required' => 'Tiêu đề phải có nhé',
                'tomtat.required' => 'Tóm tắt chapter phải có nhé',
              
                'slug_chapter.required' => 'Slug chapter phải có',
                
            ]
        );
        // $data = $request->all();
        // dd($data);
        
        $chapter = Chapter::find($id);

        //rename dir chapter in google drive
        $dir = '/';
        $recursive = true; // Get subdirectories also?
        $contents = collect(Storage::disk('google')->listContents($dir, $recursive));

        $dir_chapter = $contents->where('type', '=', 'dir')
            ->where('filename', '=', $chapter->slug_chapter)
            ->first(); 
       
        //dd($dir_chapter);
        if ( ! $dir_chapter) {
            return redirect()->back()->with('status','Thư mục truyện tranh không tồn tại trong google drive,check lại nhé.');
        }
       
        Storage::disk('google')->move($dir_chapter['basename'], "".$data['slug_chapter']."");
        //update db
        $chapter->tieude = $data['tieude'];
        $chapter->slug_chapter = $data['slug_chapter'];
        $chapter->updated_at = Carbon::now('Asia/Ho_Chi_Minh');
        $chapter->tomtat = $data['tomtat'];
        $chapter->noidung = 'noidungtruyentranh';
        $chapter->kichhoat = $data['kichhoat'];
        $chapter->truyen_id = $data['truyen_id'];
        $chapter->loaichapter = 'truyentranh';
        $chapter->save();

        return redirect()->back()->with('status','Cập nhật chapter truyện tranh thành công');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

        $chapter = Chapter::find($id);
        //delete chapter dir in ggdrive
        $dir = '/';
        $recursive = true; // Get subdirectories also?
        $contents = collect(Storage::disk('google')->listContents($dir, $recursive));

        $directory = $contents
            ->where('type', '=', 'dir')
            ->where('filename', '=', $chapter->slug_chapter)
        ->first(); // there can be duplicate file names!
        if($directory){
        Storage::disk('google')->deleteDirectory($directory['path']);
        }
        $fileChapter = FileGGDrive::where('chapter_id',$chapter->id)->delete();
        //delete into db
        Chapter::find($id)->delete();
        return redirect()->back()->with('status','Xóa chapter thành công');
    }
    public function delete_file($filename,$extension,$timestamp){
        $dir = '/';
        $recursive = true; // Get subdirectories also?
        $contents = collect(Storage::disk('google')->listContents($dir, $recursive));

        $file = $contents
            ->where('type', '=', 'file')

resources/views/admincp/chaptertranh/create.blade.php
@extends('layouts.app')

@section('content')

@include('layouts.nav')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Thêm chapter truyện tranh</div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    
                    <form method="POST" action="{{route('chaptertranh.store')}}" enctype='multipart/form-data'>
                        @csrf
                      <div class="form-group">
                        <label for="exampleInputEmail1">Tên chapter</label>
                        <input type="text" class="form-control" value="{{old('tieude')}}" onkeyup="ChangeToSlug();" name="tieude" id="slug" aria-describedby="emailHelp" placeholder="">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Slug chapter</label>
                        <input type="text" class="form-control" value="{{old('slug_chapter')}}" name="slug_chapter" id="convert_slug" aria-describedby="emailHelp" placeholder="">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Tóm tắt chapter</label>
                        <input type="text" class="form-control" value="{{old('tomtat')}}" name="tomtat" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Hình ảnh Nội dung</label>
                        <input type="file" multiple class="form-control-file" name="files[]">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Thuộc truyện</label>
                         <select name="truyen_id" class="custom-select">
                          @foreach($truyen as $key => $value)
                          <option value="{{$value->id}}">{{$value->tentruyen}}</option>
                          @endforeach
                        </select>
                        
                      </div>

                       <div class="form-group">
                        <label for="exampleInputEmail1">Kích hoạt</label>
                        <select name="kichhoat" class="custom-select">
                          <option value="0">Kích hoạt</option>
                          <option value="1">Không kích hoạt</option>
                        </select>
                        </div>
                     
                      <button type="submit" name="themdanhmuc" class="btn btn-primary">Thêm</button>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admincp/chaptertranh/edit.blade.php
@extends('layouts.app')

@section('content')

@include('layouts.nav')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Cập nhật chapter truyện tranh</div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    
                    <form method="POST" action="{{route('chaptertranh.update',[$chapter->id])}}">
                      @method('PUT')
                        @csrf
                      <div class="form-group">
                        <label for="exampleInputEmail1">Tên chapter</label>
                        <input type="text" class="form-control" value="{{$chapter->tieude}}" onkeyup="ChangeToSlug();" name="tieude" id="slug" aria-describedby="emailHelp" placeholder="">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Slug chapter</label>
                        <input type="text" class="form-control" value="{{$chapter->slug_chapter}}" name="slug_chapter" id="convert_slug" aria-describedby="emailHelp" placeholder="">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Tóm tắt chapter</label>
                        <input type="text" class="form-control" value="{{$chapter->tomtat}}" name="tomtat" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="">
                        
                      </div>
                     {{--  <div class="form-group">
                        <label for="exampleInputEmail1">Nội dung</label>
                        <textarea name="noidung" id="noidung_chapter" class="form-control" rows="5" style="resize: none">{{$chapter->noidung}}</textarea>
                        
                      </div> --}}
                      <div class="form-group">
                        <label for="exampleInputEmail1">Thuộc truyện</label>
                         <select name="truyen_id" class="custom-select">
                          @foreach($truyen as $key => $value)
                          <option {{ $chapter->truyen_id==$value->id ? 'selected' : '' }} value="{{$value->id}}">{{$value->tentruyen}}</option>
                          @endforeach
                        </select>
                        
                      </div>

                       <div class="form-group">
                        <label for="exampleInputEmail1">Kích hoạt</label>
                        <select name="kichhoat" class="custom-select">
                          @if($chapter->kichhoat==0)
                          <option selected value="0">Kích hoạt</option>
                          <option value="1">Không kích hoạt</option>
                          @else
                          <option  value="0">Kích hoạt</option>
                          <option selected value="1">Không kích hoạt</option>
                          @endif
                        </select>
                        </div>
                     
                      <button type="submit" name="themdanhmuc" class="btn btn-primary">Cập nhật</button>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admincp/chaptertranh/index.blade.php
@extends('layouts.app')

@section('content')

@include('layouts.nav')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Liệt kê chapter truyện tranh</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">Tên chapter</th>
                          <th scope="col">Slug chapter</th>
                          <th scope="col">Tóm tắt</th>
                          <th scope="col">Thuộc Truyện</th>
                          <th scope="col">Kích hoạt</th>
                          <th scope="col">Quản lý</th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach($chapter as $key => $chap)
                        <tr>
                          <th scope="row">{{$key}}</th>
                          <td>{{$chap->tieude}}</td>
                          <td><a href="{{url('/chapter_truyentranh/'.$chap->slug_chapter)}}">{{$chap->slug_chapter}}</a></td>
                          <td>{{$chap->tomtat}}</td>
                          <td>{{$chap->truyen->tentruyen}}</td>
                          <td>
                              @if($chap->kichhoat==0)
                                <span class="text text-success">Kích hoạt</span> 
                              @else
                                <span class="text text-danger">Không Kích hoạt</span> 
                              @endif

                          </td>
                          <td>
                                <a href="{{route('chaptertranh.edit',[$chap->id])}}" class="btn btn-primary ">Edit</a>

                              <form action="{{route('chaptertranh.destroy',[$chap->id])}}" method="POST">
                                @method('DELETE')
                                @csrf
                                <button onclick="return confirm('Bạn muốn xóa chapter truyện này không?');" class="btn btn-danger">Delete</button>
                                  
                              </form>
                          </td>
                        </tr>
                        @endforeach
                      </tbody>
                    </table>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admincp/chaptertranh/view.blade.php
@extends('layouts.app')

@section('content')

@include('layouts.nav')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Xem truyện tranh</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                  	<ul style="list-style: none">

					@foreach($files as $key => $file)
						<h4>{{$file['filename']}}</h4>
						<li>{{$key}} - <a onclick="return confirm('Bạn muốn xóa tranh truyện này không?');" href="{{url('delete-file/'.$file['filename'].'/'.$file['extension'].'/'.$file['timestamp'])}}">Delete file</a><img src="https://drive.google.com/uc?id={{$file['basename']}}" width="200" height="200"></li>
					@endforeach
					</ul>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection