routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\DanhmucController;
use App\Http\Controllers\TruyenController;
use App\Http\Controllers\ChapterController;
use App\Http\Controllers\ChapterTranhController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\TheloaiController;
use App\Http\Controllers\GoogleController;
use App\Http\Controllers\FacebookController;
use App\Http\Controllers\InformationController;
use App\Http\Controllers\TruyenTranhController;
use App\Http\Controllers\SachController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\GoogleDrive;
use App\Http\Controllers\Auth\LoginController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [IndexController::class,'home']);
Route::get('/sachtruyen_admin', [LoginController::class,'login'])->name('login');
Route::get('/danh-muc/{slug}', [IndexController::class,'danhmuc']);
Route::get('/xem-truyen/{slug}', [IndexController::class,'xemtruyen']);
Route::get('/xem-chapter/{slug_truyen}/{slug}', [IndexController::class,'xemchapter']);
Route::get('/xem-truyen-tranh/{slug_truyen}/{slug}', [IndexController::class,'xemtruyentranh']);
Route::get('/the-loai/{slug}', [IndexController::class,'theloai']);

Route::get('/doc-sach', [IndexController::class,'docsach']);
Route::post('/xemsachnhanh', [IndexController::class,'xemsachnhanh']);

Route::get('/truyen-tranh', [IndexController::class,'truyentranh']);
Route::get('/truyen-tranh/{slug}', [IndexController::class,'truyentranh']);
Route::get('/tag/{tag}', [IndexController::class,'tag']);
Route::post('/show-tranh', [IndexController::class,'show_tranh']);
Route::post('/autocomplete-ajax',[IndexController::class,'autocomplete_ajax']);
Route::post('/tim-kiem', [IndexController::class,'timkiem']);
Route::post('/truyennoibat', [TruyenController::class,'truyennoibat']);
Route::post('/tabs-danhmuc', [IndexController::class,'tabs_danhmuc']);
Route::get('/kytu/{kytu}', [IndexController::class,'kytu']);

Route::get('dang-ky', [IndexController::class,'dangky'])->name('dang-ky');
Route::get('dang-nhap', [IndexController::class,'dangnhap'])->name('dang-nhap');
Route::get('dang-xuat', [IndexController::class,'sign_out'])->name('dang-xuat');
Route::get('yeu-thich', [IndexController::class,'yeu_thich'])->name('yeu-thich');
Route::get('xoayeuthich/{id}', [IndexController::class,'xoayeuthich'])->name('xoayeuthich');
Route::post('register-publisher', [IndexController::class,'register_publisher'])->name('register-publisher');
Route::post('login-publisher', [IndexController::class,'login_publisher'])->name('login-publisher');
Route::post('themyeuthich', [IndexController::class,'themyeuthich'])->name('themyeuthich');
Route::post('comment', [IndexController::class,'comment'])->name('comment');
Auth::routes();
// Auth::routes([
//   'register' => false, // Registration Routes...
//   'reset' => false, // Password Reset Routes...
//   'verify' => false, // Email Verification Routes...
  
// ]);
Route::group(['middleware' => ['auth']], function() {
	
	Route::resource('/danhmuc', DanhmucController::class);
	Route::resource('/truyen', TruyenController::class);
	Route::resource('/sach', SachController::class);
	Route::resource('/chapter', ChapterController::class);
	Route::resource('/theloai', TheloaiController::class);
	Route::resource('/information', InformationController::class);
	Route::resource('/truyentranh', TruyenTranhController::class);
	Route::resource('/chaptertranh', ChapterTranhController::class);
	Route::get('chapter_truyentranh/{slug}', [ChapterTranhController::class, 'chapter_truyentranh']);
	Route::get('delete-file/{filename}/{extension}/{timestamp}', [ChapterTranhController::class, 'delete_file']);

	Route::get('/home', [UserController::class, 'index'])->name('home');
	Route::get('/impersonate/user/{id}', [UserController::class,'impersonate']);
	Route::get('/user/stopImpersonate', [UserController::class,'stopImpersonate']);


	Route::get('list-comment', [TruyenController::class,'list_comment'])->name('list-comment');
	Route::post('active_comment', [TruyenController::class,'active_comment'])->name('active_comment');
	
});

Route::get('auth/google', [GoogleController::class, 'redirectToGoogle']);
Route::get('auth/google/callback', [GoogleController::class, 'handleGoogleCallback']);

Route::get('auth/facebook', [FacebookController::class, 'redirectToFacebook']);
Route::get('auth/facebook/callback', [FacebookController::class, 'handleFacebookCallback']);

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
     \UniSharp\LaravelFilemanager\Lfm::routes();
 });

Route::get('/storage-link', function(){
    return Artisan::call('storage:link');
    
});
Route::get('/create-sitemap', function(){
    return Artisan::call('sitemap:create');
   
});
Route::get('/custom_error', function(){
    return Artisan::call('php artisan vendor:publish --tag=laravel-errors');
  
});

Route::get('/assignRole/{id}', [HomeController::class, 'assignRole']);
Route::post('/insert_roles/{id}', [HomeController::class, 'insert_roles']);

app/Models/DanhmucTruyen.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class DanhmucTruyen extends Model
{
    use HasFactory;

    public $timestamps = false; //set time to false
    protected $fillable = [
    	'tendanhmuc', 'mota', 'kichhoat','slug_danhmuc','tukhoa','created_at','updated_at'
    ];
    protected $primaryKey = 'id';
 	protected $table = 'danhmuc';

 	public function truyen(){
 		return $this->hasMany('App\Models\Truyen');
 	}
 	public function nhieutruyen(){
 		return $this->belongsToMany(Truyen::class,'thuocdanh','danhmuc_id','truyen_id');
 	}
}

resources/views/admincp/danhmuctruyen/create.blade.php
@extends('layouts.app')

@section('content')

@include('layouts.nav')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Thêm danh mục truyện</div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    
                    <form method="POST" action="{{route('danhmuc.store')}}"  enctype='multipart/form-data'>
                        @csrf
                      <div class="form-group">
                        <label for="exampleInputEmail1">Tên danh mục</label>
                        <input type="text" class="form-control" value="{{old('tendanhmuc')}}" onkeyup="ChangeToSlug();" name="tendanhmuc" id="slug" aria-describedby="emailHelp" placeholder="Tên danh mục...">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Từ khóa</label>
                        <input type="text" class="form-control" value="{{old('tukhoa')}}" name="tukhoa"  aria-describedby="emailHelp" placeholder="">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Slug danh mục</label>
                        <input type="text" class="form-control" value="{{old('slug_danhmuc')}}" name="slug_danhmuc" id="convert_slug" aria-describedby="emailHelp" placeholder="Tên danh mục...">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Mô tả danh mục</label>
                        <input type="text" class="form-control" value="{{old('mota')}}" name="mota" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Mô tả danh mục">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Hình ảnh danh mục</label>
                        <input type="file" class="form-control-file" name="hinhanh">
                        
                      </div>
                       <div class="form-group">
                        <label for="exampleInputEmail1">Kích hoạt</label>
                        <select name="kichhoat" class="custom-select">
                          <option value="0">Kích hoạt</option>
                          <option value="1">Không kích hoạt</option>
                        </select>
                        </div>
                     
                      <button type="submit" name="themdanhmuc" class="btn btn-primary">Thêm</button>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admincp/danhmuctruyen/edit.blade.php
@extends('layouts.app')

@section('content')

@include('layouts.nav')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Cập nhật danh mục truyện</div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    
                    <form method="POST" action="{{route('danhmuc.update',[$danhmuc->id])}}" enctype='multipart/form-data'>
                        @method('PUT')
                        @csrf
                      <div class="form-group">
                        <label for="exampleInputEmail1">Tên danh mục</label>
                        <input type="text" class="form-control" value="{{$danhmuc->tendanhmuc}}" onkeyup="ChangeToSlug();" name="tendanhmuc" id="slug" aria-describedby="emailHelp" placeholder="Tên danh mục...">
                        
                      </div>
                       <div class="form-group">
                        <label for="exampleInputEmail1">Từ khóa</label>
                        <input type="text" class="form-control" value="{{$danhmuc->tukhoa}}" name="tukhoa"  aria-describedby="emailHelp" placeholder="">
                        
                      </div>
                       <div class="form-group">
                        <label for="exampleInputEmail1">Slug danh mục</label>
                        <input type="text" class="form-control" value="{{$danhmuc->slug_danhmuc}}" name="slug_danhmuc" id="convert_slug" aria-describedby="emailHelp" placeholder="Slug danh mục...">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Mô tả danh mục</label>
                        <input type="text" class="form-control" value="{{$danhmuc->mota}}" name="mota" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Mô tả danh mục">
                        
                      </div>
                       <div class="form-group">
                        <label for="exampleInputEmail1">Hình ảnh danh mục</label>
                        <input type="file" class="form-control-file" name="hinhanh">
                        <img src="{{asset('public/uploads/danhmuc/'.$danhmuc->hinhanh)}}" height="250" width="180">  
                      </div>
                       <div class="form-group">
                        <label for="exampleInputEmail1">Kích hoạt</label>
                        <select name="kichhoat" class="custom-select">
                          @if($danhmuc->kichhoat==0)
                          <option selected value="0">Kích hoạt</option>
                          <option value="1">Không kích hoạt</option>
                          @else
                          <option  value="0">Kích hoạt</option>
                          <option selected value="1">Không kích hoạt</option>
                          @endif
                        </select>
                        </div>
                     
                      <button type="submit" name="themdanhmuc" class="btn btn-primary">Cập nhật</button>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admincp/danhmuctruyen/index.blade.php
@extends('layouts.app')

@section('content')

@include('layouts.nav')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Liệt kê danh mục truyện</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">Tên danh mục</th>
                           <th scope="col">Hình ảnh</th>
                          <th scope="col">Slug danh mục</th>
                          <th scope="col">Mô tả</th>
                          <th scope="col">Kích hoạt</th>
                          <th scope="col">Quản lý</th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach($danhmuctruyen as $key => $danhmuc)
                        <tr>
                          <th scope="row">{{$key}}</th>
                          <td>{{$danhmuc->tendanhmuc}}</td>
                          <td><img src="{{asset('public/uploads/danhmuc/'.$danhmuc->hinhanh)}}" height="250" width="180">  </td>
                          <td>{{$danhmuc->slug_danhmuc}}</td>
                          <td>{{$danhmuc->mota}}</td>
                          <td>
                              @if($danhmuc->kichhoat==0)
                                <span class="text text-success">Kích hoạt</span> 
                              @else
                                <span class="text text-danger">Không Kích hoạt</span> 
                              @endif

                          </td>
                          <td>
                                <a href="{{route('danhmuc.edit',[$danhmuc->id])}}" class="btn btn-primary ">Edit</a>

                              <form action="{{route('danhmuc.destroy',[$danhmuc->id])}}" method="POST">
                                @method('DELETE')
                                @csrf
                                <button onclick="return confirm('Bạn muốn xóa danh mục truyện này không?');" class="btn btn-danger">Delete</button>
                                  
                              </form>
                          </td>
                        </tr>
                        @endforeach
                      </tbody>
                    </table>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection