routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\DanhmucController;
use App\Http\Controllers\TruyenController;
use App\Http\Controllers\ChapterController;
use App\Http\Controllers\ChapterTranhController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\TheloaiController;
use App\Http\Controllers\GoogleController;
use App\Http\Controllers\FacebookController;
use App\Http\Controllers\InformationController;
use App\Http\Controllers\TruyenTranhController;
use App\Http\Controllers\SachController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\GoogleDrive;
use App\Http\Controllers\Auth\LoginController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [IndexController::class,'home']);
Route::get('/sachtruyen_admin', [LoginController::class,'login'])->name('login');
Route::get('/danh-muc/{slug}', [IndexController::class,'danhmuc']);
Route::get('/xem-truyen/{slug}', [IndexController::class,'xemtruyen']);
Route::get('/xem-chapter/{slug_truyen}/{slug}', [IndexController::class,'xemchapter']);
Route::get('/xem-truyen-tranh/{slug_truyen}/{slug}', [IndexController::class,'xemtruyentranh']);
Route::get('/the-loai/{slug}', [IndexController::class,'theloai']);

Route::get('/doc-sach', [IndexController::class,'docsach']);
Route::post('/xemsachnhanh', [IndexController::class,'xemsachnhanh']);

Route::get('/truyen-tranh', [IndexController::class,'truyentranh']);
Route::get('/truyen-tranh/{slug}', [IndexController::class,'truyentranh']);
Route::get('/tag/{tag}', [IndexController::class,'tag']);
Route::post('/show-tranh', [IndexController::class,'show_tranh']);
Route::post('/autocomplete-ajax',[IndexController::class,'autocomplete_ajax']);
Route::post('/tim-kiem', [IndexController::class,'timkiem']);
Route::post('/truyennoibat', [TruyenController::class,'truyennoibat']);
Route::post('/tabs-danhmuc', [IndexController::class,'tabs_danhmuc']);
Route::get('/kytu/{kytu}', [IndexController::class,'kytu']);

Route::get('dang-ky', [IndexController::class,'dangky'])->name('dang-ky');
Route::get('dang-nhap', [IndexController::class,'dangnhap'])->name('dang-nhap');
Route::get('dang-xuat', [IndexController::class,'sign_out'])->name('dang-xuat');
Route::get('yeu-thich', [IndexController::class,'yeu_thich'])->name('yeu-thich');
Route::get('xoayeuthich/{id}', [IndexController::class,'xoayeuthich'])->name('xoayeuthich');
Route::post('register-publisher', [IndexController::class,'register_publisher'])->name('register-publisher');
Route::post('login-publisher', [IndexController::class,'login_publisher'])->name('login-publisher');
Route::post('themyeuthich', [IndexController::class,'themyeuthich'])->name('themyeuthich');
Route::post('comment', [IndexController::class,'comment'])->name('comment');
Auth::routes();
// Auth::routes([
//   'register' => false, // Registration Routes...
//   'reset' => false, // Password Reset Routes...
//   'verify' => false, // Email Verification Routes...
  
// ]);
Route::group(['middleware' => ['auth']], function() {
	
	Route::resource('/danhmuc', DanhmucController::class);
	Route::resource('/truyen', TruyenController::class);
	Route::resource('/sach', SachController::class);
	Route::resource('/chapter', ChapterController::class);
	Route::resource('/theloai', TheloaiController::class);
	Route::resource('/information', InformationController::class);
	Route::resource('/truyentranh', TruyenTranhController::class);
	Route::resource('/chaptertranh', ChapterTranhController::class);
	Route::get('chapter_truyentranh/{slug}', [ChapterTranhController::class, 'chapter_truyentranh']);
	Route::get('delete-file/{filename}/{extension}/{timestamp}', [ChapterTranhController::class, 'delete_file']);

	Route::get('/home', [UserController::class, 'index'])->name('home');
	Route::get('/impersonate/user/{id}', [UserController::class,'impersonate']);
	Route::get('/user/stopImpersonate', [UserController::class,'stopImpersonate']);


	Route::get('list-comment', [TruyenController::class,'list_comment'])->name('list-comment');
	Route::post('active_comment', [TruyenController::class,'active_comment'])->name('active_comment');
	
});

Route::get('auth/google', [GoogleController::class, 'redirectToGoogle']);
Route::get('auth/google/callback', [GoogleController::class, 'handleGoogleCallback']);

Route::get('auth/facebook', [FacebookController::class, 'redirectToFacebook']);
Route::get('auth/facebook/callback', [FacebookController::class, 'handleFacebookCallback']);

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
     \UniSharp\LaravelFilemanager\Lfm::routes();
 });

Route::get('/storage-link', function(){
    return Artisan::call('storage:link');
    
});
Route::get('/create-sitemap', function(){
    return Artisan::call('sitemap:create');
   
});
Route::get('/custom_error', function(){
    return Artisan::call('php artisan vendor:publish --tag=laravel-errors');
  
});

Route::get('/assignRole/{id}', [HomeController::class, 'assignRole']);
Route::post('/insert_roles/{id}', [HomeController::class, 'insert_roles']);

app/Models/Chapter.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Chapter extends Model
{
    use HasFactory;

    public $timestamps = false; //set time to false
    protected $fillable = [
    	'truyen_id', 'tomtat', 'tieude','noidung','kichhoat','slug_chapter','loaichapter'
    ];
    protected $primaryKey = 'id';
 	protected $table = 'chapter';

 	public function truyen(){
 		return $this->belongsTo('App\Models\Truyen');
 	}
 	
}

app/Http/Controllers/ChapterController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Chapter;
use App\Models\Truyen;
use Carbon\Carbon;
class ChapterController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $chapter = Chapter::with('truyen')->where('loaichapter','=',NULL)->orderBy('id','DESC')->get();
        //dd($chapter);
        return view('admincp.chapter.index')->with(compact('chapter'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $truyen = Truyen::orderBy('id','DESC')->where('loaitruyen','=',NULL)->get();
        return view('admincp.chapter.create')->with(compact('truyen'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate(
            [
                'tieude' => 'required|max:255',
                'slug_chapter' => 'required|max:255',

                
                'noidung' => 'required',
                'tomtat' => 'required',
                'kichhoat' => 'required',
                'truyen_id' => 'required',
            ],
            [
                'slug_chapter.unique' => 'Slug đã có ,xin điền slug khác',
                'tieude.unique' => 'Tiêu đề đã có ,xin điền tiêu đề khác',
                'tieude.required' => 'Tiêu đề phải có nhé',
                'tomtat.required' => 'Tóm tắt chapter phải có nhé',
                'noidung.required' => 'Nội dung chapter phải có nhé',
                'slug_chapter.required' => 'Slug chapter phải có',
                
            ]
        );
        // $data = $request->all();
        // dd($data);
        $chapter = new Chapter();
        $chapter->tieude = $data['tieude'];
        $chapter->slug_chapter = $data['slug_chapter'];
        $chapter->created_at = Carbon::now('Asia/Ho_Chi_Minh');
        $chapter->tomtat = $data['tomtat'];
        $chapter->noidung = $data['noidung'];
        $chapter->kichhoat = $data['kichhoat'];
        $chapter->truyen_id = $data['truyen_id'];
        $chapter->save();

        return redirect()->back()->with('status','Thêm chapter thành công');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $chapter = Chapter::find($id);
        $truyen = Truyen::where('loaitruyen','=',NULL)->orderBy('id','DESC')->get();
        return view('admincp.chapter.edit')->with(compact('truyen','chapter'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $data = $request->validate(
            [
                'tieude' => 'required|max:255',
                'slug_chapter' => 'required|max:255',
                'noidung' => 'required',
                'tomtat' => 'required',
                'kichhoat' => 'required',
                'truyen_id' => 'required',
            ],
            [
                'slug_chapter.unique' => 'Slug đã có ,xin điền slug khác',
                'tieude.unique' => 'Tiêu đề đã có ,xin điền tiêu đề khác',
                'tieude.required' => 'Tiêu đề phải có nhé',
                'tomtat.required' => 'Tóm tắt chapter phải có nhé',
                'noidung.required' => 'Nội dung chapter phải có nhé',
                'slug_chapter.required' => 'Slug chapter phải có',
                
            ]
        );
        // $data = $request->all();
        // dd($data);
        $chapter = Chapter::find($id);
        $chapter->tieude = $data['tieude'];
        $chapter->slug_chapter = $data['slug_chapter'];
        $chapter->updated_at = Carbon::now('Asia/Ho_Chi_Minh');
        $chapter->tomtat = $data['tomtat'];
        $chapter->noidung = $data['noidung'];
        $chapter->kichhoat = $data['kichhoat'];
        $chapter->truyen_id = $data['truyen_id'];
        $chapter->save();

        return redirect()->back()->with('status','Cập nhật chapter thành công');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Chapter::find($id)->delete();
        return redirect()->back()->with('status','Xóa chapter thành công');
    }
}

resources/views/admincp/chapter/create.blade.php
@extends('layouts.app')

@section('content')

@include('layouts.nav')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Thêm chapter truyện</div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    
                    <form method="POST" action="{{route('chapter.store')}}">
                        @csrf
                      <div class="form-group">
                        <label for="exampleInputEmail1">Tên chapter</label>
                        <input type="text" class="form-control" value="{{old('tieude')}}" onkeyup="ChangeToSlug();" name="tieude" id="slug" aria-describedby="emailHelp" placeholder="">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Slug chapter</label>
                        <input type="text" class="form-control" value="{{old('slug_chapter')}}" name="slug_chapter" id="convert_slug" aria-describedby="emailHelp" placeholder="">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Tóm tắt chapter</label>
                        <input type="text" class="form-control" value="{{old('tomtat')}}" name="tomtat" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Nội dung</label>
                        <textarea name="noidung" id="noidung_chapter" class="form-control" rows="5" style="resize: none"></textarea>
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Thuộc truyện</label>
                         <select name="truyen_id" class="custom-select">
                          @foreach($truyen as $key => $value)
                          <option value="{{$value->id}}">{{$value->tentruyen}}</option>
                          @endforeach
                        </select>
                        
                      </div>

                       <div class="form-group">
                        <label for="exampleInputEmail1">Kích hoạt</label>
                        <select name="kichhoat" class="custom-select">
                          <option value="0">Kích hoạt</option>
                          <option value="1">Không kích hoạt</option>
                        </select>
                        </div>
                     
                      <button type="submit" name="themdanhmuc" class="btn btn-primary">Thêm</button>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admincp/chapter/edit.blade.php
@extends('layouts.app')

@section('content')

@include('layouts.nav')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Cập nhật chapter truyện</div>
                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif
                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    
                    <form method="POST" action="{{route('chapter.update',[$chapter->id])}}">
                      @method('PUT')
                        @csrf
                      <div class="form-group">
                        <label for="exampleInputEmail1">Tên chapter</label>
                        <input type="text" class="form-control" value="{{$chapter->tieude}}" onkeyup="ChangeToSlug();" name="tieude" id="slug" aria-describedby="emailHelp" placeholder="">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Slug chapter</label>
                        <input type="text" class="form-control" value="{{$chapter->slug_chapter}}" name="slug_chapter" id="convert_slug" aria-describedby="emailHelp" placeholder="">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Tóm tắt chapter</label>
                        <input type="text" class="form-control" value="{{$chapter->tomtat}}" name="tomtat" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="">
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Nội dung</label>
                        <textarea name="noidung" id="noidung_chapter" class="form-control" rows="5" style="resize: none">{{$chapter->noidung}}</textarea>
                        
                      </div>
                      <div class="form-group">
                        <label for="exampleInputEmail1">Thuộc truyện</label>
                         <select name="truyen_id" class="custom-select">
                          @foreach($truyen as $key => $value)
                          <option {{ $chapter->truyen_id==$value->id ? 'selected' : '' }} value="{{$value->id}}">{{$value->tentruyen}}</option>
                          @endforeach
                        </select>
                        
                      </div>

                       <div class="form-group">
                        <label for="exampleInputEmail1">Kích hoạt</label>
                        <select name="kichhoat" class="custom-select">
                          @if($chapter->kichhoat==0)
                          <option selected value="0">Kích hoạt</option>
                          <option value="1">Không kích hoạt</option>
                          @else
                          <option  value="0">Kích hoạt</option>
                          <option selected value="1">Không kích hoạt</option>
                          @endif
                        </select>
                        </div>
                     
                      <button type="submit" name="themdanhmuc" class="btn btn-primary">Cập nhật</button>
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admincp/chapter/index.blade.php
@extends('layouts.app')

@section('content')

@include('layouts.nav')
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Liệt kê chapter</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    <table class="table table-striped">
                      <thead>
                        <tr>
                          <th scope="col">#</th>
                          <th scope="col">Tên chapter</th>
                          <th scope="col">Slug chapter</th>
                          <th scope="col">Tóm tắt</th>
                          <th scope="col">Thuộc Truyện</th>
                          <th scope="col">Kích hoạt</th>
                          <th scope="col">Quản lý</th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach($chapter as $key => $chap)
                        <tr>
                          <th scope="row">{{$key}}</th>
                          <td>{{$chap->tieude}}</td>
                          <td>{{$chap->slug_chapter}}</td>
                          <td>{{$chap->tomtat}}</td>

                        
                            @if(isset($chap->truyen->tentruyen))
                              <td>{{$chap->truyen->tentruyen}}</td>
                            @else
                              <td></td>
                            @endif
                            
                         
                          <td>
                              @if($chap->kichhoat==0)
                                <span class="text text-success">Kích hoạt</span> 
                              @else
                                <span class="text text-danger">Không Kích hoạt</span> 
                              @endif

                          </td>
                          <td>
                                <a href="{{route('chapter.edit',[$chap->id])}}" class="btn btn-primary ">Edit</a>

                              <form action="{{route('chapter.destroy',[$chap->id])}}" method="POST">
                                @method('DELETE')
                                @csrf
                                <button onclick="return confirm('Bạn muốn xóa chapter truyện này không?');" class="btn btn-danger">Delete</button>
                                  
                              </form>
                          </td>
                        </tr>
                        @endforeach
                      </tbody>
                    </table>
                    
                </div>
            </div>
        </div>
    </div>
</div>
@endsection