routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\DanhmucController;
use App\Http\Controllers\TruyenController;
use App\Http\Controllers\ChapterController;
use App\Http\Controllers\ChapterTranhController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\TheloaiController;
use App\Http\Controllers\GoogleController;
use App\Http\Controllers\FacebookController;
use App\Http\Controllers\InformationController;
use App\Http\Controllers\TruyenTranhController;
use App\Http\Controllers\SachController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\GoogleDrive;
use App\Http\Controllers\Auth\LoginController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [IndexController::class,'home']);
Route::get('/sachtruyen_admin', [LoginController::class,'login'])->name('login');
Route::get('/danh-muc/{slug}', [IndexController::class,'danhmuc']);
Route::get('/xem-truyen/{slug}', [IndexController::class,'xemtruyen']);
Route::get('/xem-chapter/{slug_truyen}/{slug}', [IndexController::class,'xemchapter']);
Route::get('/xem-truyen-tranh/{slug_truyen}/{slug}', [IndexController::class,'xemtruyentranh']);
Route::get('/the-loai/{slug}', [IndexController::class,'theloai']);

Route::get('/doc-sach', [IndexController::class,'docsach']);
Route::post('/xemsachnhanh', [IndexController::class,'xemsachnhanh']);

Route::get('/truyen-tranh', [IndexController::class,'truyentranh']);
Route::get('/truyen-tranh/{slug}', [IndexController::class,'truyentranh']);
Route::get('/tag/{tag}', [IndexController::class,'tag']);
Route::post('/show-tranh', [IndexController::class,'show_tranh']);
Route::post('/autocomplete-ajax',[IndexController::class,'autocomplete_ajax']);
Route::post('/tim-kiem', [IndexController::class,'timkiem']);
Route::post('/truyennoibat', [TruyenController::class,'truyennoibat']);
Route::post('/tabs-danhmuc', [IndexController::class,'tabs_danhmuc']);
Route::get('/kytu/{kytu}', [IndexController::class,'kytu']);

Route::get('dang-ky', [IndexController::class,'dangky'])->name('dang-ky');
Route::get('dang-nhap', [IndexController::class,'dangnhap'])->name('dang-nhap');
Route::get('dang-xuat', [IndexController::class,'sign_out'])->name('dang-xuat');
Route::get('yeu-thich', [IndexController::class,'yeu_thich'])->name('yeu-thich');
Route::get('xoayeuthich/{id}', [IndexController::class,'xoayeuthich'])->name('xoayeuthich');
Route::post('register-publisher', [IndexController::class,'register_publisher'])->name('register-publisher');
Route::post('login-publisher', [IndexController::class,'login_publisher'])->name('login-publisher');
Route::post('themyeuthich', [IndexController::class,'themyeuthich'])->name('themyeuthich');
Route::post('comment', [IndexController::class,'comment'])->name('comment');
Auth::routes();
// Auth::routes([
//   'register' => false, // Registration Routes...
//   'reset' => false, // Password Reset Routes...
//   'verify' => false, // Email Verification Routes...
  
// ]);
Route::group(['middleware' => ['auth']], function() {
	
	Route::resource('/danhmuc', DanhmucController::class);
	Route::resource('/truyen', TruyenController::class);
	Route::resource('/sach', SachController::class);
	Route::resource('/chapter', ChapterController::class);
	Route::resource('/theloai', TheloaiController::class);
	Route::resource('/information', InformationController::class);
	Route::resource('/truyentranh', TruyenTranhController::class);
	Route::resource('/chaptertranh', ChapterTranhController::class);
	Route::get('chapter_truyentranh/{slug}', [ChapterTranhController::class, 'chapter_truyentranh']);
	Route::get('delete-file/{filename}/{extension}/{timestamp}', [ChapterTranhController::class, 'delete_file']);

	Route::get('/home', [UserController::class, 'index'])->name('home');
	Route::get('/impersonate/user/{id}', [UserController::class,'impersonate']);
	Route::get('/user/stopImpersonate', [UserController::class,'stopImpersonate']);


	Route::get('list-comment', [TruyenController::class,'list_comment'])->name('list-comment');
	Route::post('active_comment', [TruyenController::class,'active_comment'])->name('active_comment');
	
});

Route::get('auth/google', [GoogleController::class, 'redirectToGoogle']);
Route::get('auth/google/callback', [GoogleController::class, 'handleGoogleCallback']);

Route::get('auth/facebook', [FacebookController::class, 'redirectToFacebook']);
Route::get('auth/facebook/callback', [FacebookController::class, 'handleFacebookCallback']);

Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
     \UniSharp\LaravelFilemanager\Lfm::routes();
 });

Route::get('/storage-link', function(){
    return Artisan::call('storage:link');
    
});
Route::get('/create-sitemap', function(){
    return Artisan::call('sitemap:create');
   
});
Route::get('/custom_error', function(){
    return Artisan::call('php artisan vendor:publish --tag=laravel-errors');
  
});

Route::get('/assignRole/{id}', [HomeController::class, 'assignRole']);
Route::post('/insert_roles/{id}', [HomeController::class, 'insert_roles']);

app/Models/Sach.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Sach extends Model
{
	protected $dates = [
	    'created_at',
	    'updated_at',
	    // your other new column
	];
    use HasFactory;
    public $timestamps = false; //set time to false
    protected $fillable = [
    	'tensach', 'tomtat', 'kichhoat','slug_sach','hinhanh','views','created_at','updated_at','tukhoa','noidung'
    ];
    protected $primaryKey = 'id';
 	protected $table = 'sach';
}

app/Http/Controllers/SachController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Sach;
use Carbon\Carbon;

class SachController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $list_sach = Sach::orderBy('id','DESC')->get();
        return view('admincp.sach.index')->with(compact('list_sach'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admincp.sach.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->validate(
            [
                'tensach' => 'required|unique:sach|max:255',
                'slug_sach' => 'required|unique:sach|max:255',

                'hinhanh' => 'required|image|mimes:jpg,png,jpeg,gif,svg|max:2048|dimensions:min_width=100,min_height=100,max_width=2000,max_height=2000',

                'tomtat' => 'required',

                'noidung' => 'required',
              
                'tukhoa' => 'required',
               
                'kichhoat' => 'required',
              
                'views' => 'required',
                
            ],
            [
                'views.required' => 'Yêu cầu nhập lượt xem',
                'slug_sach.unique' => 'Tên sách đã có ,xin điền tên khác',
                'tensach.unique' => 'Slug sách đã có ,xin điền slug khác',
                'tensach.required' => 'Tên sách phải có nhé',
                'tukhoa.required' => 'Từ khóa sách phải có nhé',
                'noidung.required' => 'Nội dung sách phải có nhé',
                'tomtat.required' => 'Mô tả sách phải có nhé',
               
                'slug_sach.required' => 'Slug sách phải có',
                'hinhanh.required' => 'Hình ảnh sách phải có',

            ]
        );
        // $data = $request->all();
        // // dd($data);
        $sach = new Sach();
        $sach->tensach = $data['tensach'];
        $sach->tukhoa = $data['tukhoa'];
        $sach->slug_sach = $data['slug_sach'];
     
        $sach->tomtat = $data['tomtat'];
        $sach->kichhoat = $data['kichhoat'];
        $sach->noidung = $data['noidung'];
        $sach->views = $data['views'];
       
        $sach->created_at = Carbon::now('Asia/Ho_Chi_Minh');
        $sach->updated_at = Carbon::now('Asia/Ho_Chi_Minh');
      
        //them anh vao folder hinh188.jpg
        $get_image = $request->hinhanh;
        $path = 'public/uploads/sach/';
        $get_name_image = $get_image->getClientOriginalName();
        $name_image = current(explode('.',$get_name_image));
        $new_image =  $name_image.rand(0,99).'.'.$get_image->getClientOriginalExtension();
        $get_image->move($path,$new_image);
    
        $sach->hinhanh = $new_image;
        $sach->save();

        
        return redirect()->back()->with('status','Thêm sách thành công');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $sach = Sach::find($id);
        return view('admincp.sach.edit')->with(compact('sach'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $data = $request->validate(
            [
                'tensach' => 'required|max:255',
                'slug_sach' => 'required|max:255',

                'hinhanh' => 'image|mimes:jpg,png,jpeg,gif,svg|max:2048|dimensions:min_width=100,min_height=100,max_width=2000,max_height=2000',

                'tomtat' => 'required',

                'noidung' => 'required',
              
                'tukhoa' => 'required',
               
                'kichhoat' => 'required',
              
                'views' => 'required',
                
            ],
            [
                'views.required' => 'Yêu cầu nhập lượt xem',

                'tukhoa.required' => 'Từ khóa sách phải có nhé',
                'noidung.required' => 'Nội dung sách phải có nhé',
                'tomtat.required' => 'Mô tả sách phải có nhé',
               
                'slug_sach.required' => 'Slug sách phải có',
               

            ]
        );
        // $data = $request->all();
        // // dd($data);
        $sach = Sach::find($id);
        $sach->tensach = $data['tensach'];
        $sach->tukhoa = $data['tukhoa'];
        $sach->slug_sach = $data['slug_sach'];
     
        $sach->tomtat = $data['tomtat'];
        $sach->kichhoat = $data['kichhoat'];
        $sach->noidung = $data['noidung'];
        $sach->views = $data['views'];
       
        $sach->created_at = Carbon::now('Asia/Ho_Chi_Minh');
        $sach->updated_at = Carbon::now('Asia/Ho_Chi_Minh');
      
        //them anh vao folder hinh188.jpg
        $get_image = $request->hinhanh;
        if($get_image){
            $path = 'public/uploads/sach/'.$sach->hinhanh;
            if(file_exists($path)){
                unlink($path);
            }
            $path = 'public/uploads/sach/';
            $get_name_image = $get_image->getClientOriginalName();
            $name_image = current(explode('.',$get_name_image));
            $new_image =  $name_image.rand(0,99).'.'.$get_image->getClientOriginalExtension();
            $get_image->move($path,$new_image);
        
            $sach->hinhanh = $new_image;
           
        }
         $sach->save();

        return redirect()->back()->with('status','Thêm sách thành công');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $sach = Sach::find($id);
        $path = 'public/uploads/sach/'.$sach->hinhanh;
        if(file_exists($path)){
            unlink($path);
        }
      
     
        Sach::find($id)->delete();

        return redirect()->back()->with('status','Xóa sách thành công');
    }
}

resources/views/admincp/sach/create.blade.php
@extends('layouts.app')



@section('content')



@include('layouts.nav')

<div class="container">

    <div class="row justify-content-center">

        <div class="col-md-8">

            <div class="card">

                <div class="card-header">Thêm sách </div>
                

                @if ($errors->any())

                    <div class="alert alert-danger">

                        <ul>

                            @foreach ($errors->all() as $error)

                                <li>{{ $error }}</li>

                            @endforeach

                        </ul>

                    </div>

                @endif

                <div class="card-body">

                    @if (session('status'))

                        <div class="alert alert-success" role="alert">

                            {{ session('status') }}

                        </div>

                    @endif

                    

                    <form method="POST" action="{{route('sach.store')}}" enctype='multipart/form-data'>

                        @csrf

                      <div class="form-group">

                        <label for="exampleInputEmail1">Tên sách</label>

                        <input type="text" class="form-control" value="{{old('tensach')}}" onkeyup="ChangeToSlug();" name="tensach" id="slug" aria-describedby="emailHelp" placeholder="Tên sách">

                        

                      </div>
                      <div class="form-group">

                        <label for="exampleInputEmail1">Lượt xem</label>

                        <input type="text" class="form-control" value="{{old('views')}}" name="views"  aria-describedby="emailHelp" placeholder="Lượt xem">

                        

                      </div>

                       <div class="form-group">

                        <label for="exampleInputEmail1">Từ khóa</label>

                        <input type="text" class="form-control" value="{{old('tukhoa')}}" name="tukhoa"  aria-describedby="emailHelp" placeholder="">

                        

                      </div>

                     

                      <div class="form-group">

                        <label for="exampleInputEmail1">Slug sách</label>

                        <input type="text" class="form-control" value="{{old('slug_sach')}}" name="slug_sach" id="convert_slug" aria-describedby="emailHelp" placeholder="Slug sach...">

                        

                      </div>

                      <div class="form-group">

                        <label for="exampleInputEmail1">Tóm tắt sách</label>

                        <textarea name="tomtat" class="form-control" rows="5" style="resize: none"></textarea>

              

                      </div>
                      <div class="form-group">

                        <label for="exampleInputEmail1">Nội dung sách</label>

                        <textarea name="noidung" id="ckeditor_sach" class="form-control" rows="5" style="resize: none"></textarea>

              

                      </div>
                    

                 
                      <div class="form-group">

                        <label for="exampleInputEmail1">Hình ảnh sách</label>

                        <input type="file" class="form-control-file" name="hinhanh">

                        

                      </div>

                       <div class="form-group">

                        <label for="exampleInputEmail1">Kích hoạt</label>

                        <select name="kichhoat" class="custom-select">

                          <option value="0">Kích hoạt</option>

                          <option value="1">Không kích hoạt</option>

                        </select>

                        </div>

                     

                    {{--  <div class="form-group">

                        <label for="exampleInputEmail1">Truyện nổi bật/hot</label>

                        <select name="truyennoibat" class="custom-select">

                          <option value="0">Truyện mới</option>

                          <option value="1">Truyện nổi bật</option>

                          <option value="2">Truyện xem nhiều</option>

                        </select>

                      </div>
 --}}
                      <button type="submit" name="themsach" class="btn btn-primary">Thêm sách</button>

                    </form>

                    

                </div>

            </div>

        </div>

    </div>

</div>

@endsection

resources/views/admincp/sach/edit.blade.php
@extends('layouts.app')



@section('content')



@include('layouts.nav')

<div class="container">

    <div class="row justify-content-center">

        <div class="col-md-8">

            <div class="card">

                <div class="card-header">Cập nhật sách </div>
                

                @if ($errors->any())

                    <div class="alert alert-danger">

                        <ul>

                            @foreach ($errors->all() as $error)

                                <li>{{ $error }}</li>

                            @endforeach

                        </ul>

                    </div>

                @endif

                <div class="card-body">

                    @if (session('status'))

                        <div class="alert alert-success" role="alert">

                            {{ session('status') }}

                        </div>

                    @endif

                    

                    <form method="POST" action="{{route('sach.update',[$sach->id])}}" enctype='multipart/form-data'>
                      @method('PUT')

                        @csrf

                      <div class="form-group">

                        <label for="exampleInputEmail1">Tên sách</label>

                        <input type="text" class="form-control" value="{{$sach->tensach}}" onkeyup="ChangeToSlug();" name="tensach" id="slug" aria-describedby="emailHelp" placeholder="Tên sách">

                        

                      </div>
                      <div class="form-group">

                        <label for="exampleInputEmail1">Lượt xem</label>

                        <input type="text" class="form-control" value="{{$sach->views}}" name="views"  aria-describedby="emailHelp" placeholder="Lượt xem">

                        

                      </div>

                       <div class="form-group">

                        <label for="exampleInputEmail1">Từ khóa</label>

                        <input type="text" class="form-control" value="{{$sach->tukhoa}}" name="tukhoa"  aria-describedby="emailHelp" placeholder="">

                        

                      </div>

                     

                      <div class="form-group">

                        <label for="exampleInputEmail1">Slug sách</label>

                        <input type="text" class="form-control" value="{{$sach->slug_sach}}" name="slug_sach" id="convert_slug" aria-describedby="emailHelp" placeholder="Slug sach...">

                        

                      </div>

                      <div class="form-group">

                        <label for="exampleInputEmail1">Tóm tắt sách</label>

                        <textarea name="tomtat" class="form-control" rows="5" style="resize: none">{{$sach->tomtat}}</textarea>

              

                      </div>
                      <div class="form-group">

                        <label for="exampleInputEmail1">Nội dung sách</label>

                        <textarea name="noidung" id="ckeditor_sach" class="form-control" rows="5" style="resize: none">{{$sach->noidung}}</textarea>

              

                      </div>
                    

                 
                      <div class="form-group">

                        <label for="exampleInputEmail1">Hình ảnh sách</label>

                        <input type="file" class="form-control-file" name="hinhanh">
                        <img src="{{asset('public/uploads/sach/'.$sach->hinhanh)}}" height="250" width="180">
                        

                      </div>

                        <div class="form-group">

                        <label for="exampleInputEmail1">Kích hoạt</label>

                        <select name="kichhoat" class="custom-select">

                          @if($sach->kichhoat==0)

                          <option selected value="0">Kích hoạt</option>

                          <option value="1">Không kích hoạt</option>

                          @else

                          <option  value="0">Kích hoạt</option>

                          <option selected value="1">Không kích hoạt</option>

                          @endif

                        </select>

                        </div>

                     

                    {{--  <div class="form-group">

                        <label for="exampleInputEmail1">Truyện nổi bật/hot</label>

                        <select name="truyennoibat" class="custom-select">

                          <option value="0">Truyện mới</option>

                          <option value="1">Truyện nổi bật</option>

                          <option value="2">Truyện xem nhiều</option>

                        </select>

                      </div>
 --}}
                      <button type="submit" name="capnhatsach" class="btn btn-primary">Cập nhật sách</button>

                    </form>

                    

                </div>

            </div>

        </div>

    </div>

</div>

@endsection

resources/views/admincp/sach/index.blade.php
@extends('layouts.app')



@section('content')



@include('layouts.nav')

<div class="container-fluid">

    <div class="row justify-content-center">

        <div class="col-md-12">

            <div class="card">

                <div class="card-header">Liệt kê sách</div>



                <div class="card-body">
                    <div id="thongbao"></div>
                    @if (session('status'))

                        <div class="alert alert-success" role="alert">

                            {{ session('status') }}

                        </div>

                    @endif

                    <table class="table table-striped table-responsive">

                      <thead>

                        <tr>

                          <th scope="col">#</th>

                          <th scope="col">Tên sách</th>

                          <th scope="col">Hình ảnh</th>

                          <th scope="col">Slug sách</th>

                          <th scope="col">Tóm tắt</th>

                         

                          <th scope="col">Kích hoạt</th>
                          <th scope="col">Ngày tạo</th>
                         

                       

                          <th scope="col">Quản lý</th>

                        </tr>

                      </thead>

                      <tbody>

                        @foreach($list_sach as $key => $sach)

                        <tr>

                          <th scope="row">{{$key}}</th>

                          <td>{{$sach->tensach}}</td>

                          <td><img src="{{asset('public/uploads/sach/'.$sach->hinhanh)}}" height="250" width="180"></td>

                          <td>{{$sach->slug_sach}}</td>

                          <td>
                            @php  
                            $tomtat = substr($sach->tomtat, 0,200);
                            @endphp
                            {!! $tomtat!!}
                          </td>

                        
                          <td>

                              @if($sach->kichhoat==0)

                                <span class="text text-success">Kích hoạt</span> 

                              @else

                                <span class="text text-danger">Không Kích hoạt</span> 

                              @endif



                          </td>
                           <td>{{$sach->created_at}} - {{ $sach->created_at->diffForHumans()}}</td>
                             

                            
                          <td>

                                <a href="{{route('sach.edit',[$sach->id])}}" class="btn btn-primary ">Edit</a>



                              <form action="{{route('sach.destroy',[$sach->id])}}" method="POST">

                                @method('DELETE')

                                @csrf

                                <button onclick="return confirm('Bạn muốn xóa sách này không?');" class="btn btn-danger">Delete</button>

                                  

                              </form>

                          </td>

                        </tr>

                        @endforeach

                      </tbody>

                    </table>

                    

                </div>

            </div>

        </div>

    </div>

</div>

@endsection